VENDOR_FOLDER := vendor/nvidia/grouper

PRODUCT_COPY_FILES += \
	$(VENDOR_FOLDER)/proprietary/bin/tf_daemon:system/bin/tf_daemon \
	$(VENDOR_FOLDER)/proprietary/etc/firmware/nvavp_os_00001000.bin:system/etc/firmware/nvavp_os_00001000.bin \
	$(VENDOR_FOLDER)/proprietary/etc/firmware/nvavp_os_0ff00000.bin:system/etc/firmware/nvavp_os_0ff00000.bin \
	$(VENDOR_FOLDER)/proprietary/etc/firmware/nvavp_os_e0000000.bin:system/etc/firmware/nvavp_os_e0000000.bin \
	$(VENDOR_FOLDER)/proprietary/etc/firmware/nvavp_os_eff00000.bin:system/etc/firmware/nvavp_os_eff00000.bin \
	$(VENDOR_FOLDER)/proprietary/etc/firmware/nvavp_vid_ucode_alt.bin:system/etc/firmware/nvavp_vid_ucode_alt.bin \
	$(VENDOR_FOLDER)/proprietary/etc/nvcamera.conf:system/etc/nvcamera.conf \
	$(VENDOR_FOLDER)/proprietary/etc/nvram.txt:system/etc/nvram.txt \
	$(VENDOR_FOLDER)/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
	$(VENDOR_FOLDER)/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
	$(VENDOR_FOLDER)/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
	$(VENDOR_FOLDER)/proprietary/lib/hw/gralloc.tegra3.so:system/lib/hw/gralloc.tegra3.so \
	$(VENDOR_FOLDER)/proprietary/lib/hw/hwcomposer.tegra3.so:system/lib/hw/hwcomposer.tegra3.so \
	$(VENDOR_FOLDER)/proprietary/lib/libardrv_dynamic.so:system/lib/libardrv_dynamic.so \
	$(VENDOR_FOLDER)/proprietary/lib/libcgdrv.so:system/lib/libcgdrv.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvapputil.so:system/lib/libnvapputil.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvasfparserhal.so:system/lib/libnvasfparserhal.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvaviparserhal.so:system/lib/libnvaviparserhal.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvavp.so:system/lib/libnvavp.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvcamerahdr.so:system/lib/libnvcamerahdr.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvddk_2d.so:system/lib/libnvddk_2d.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvdispmgr_d.so:system/lib/libnvdispmgr_d.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvmm.so:system/lib/libnvmm.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvmm_audio.so:system/lib/libnvmm_audio.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvmm_camera.so:system/lib/libnvmm_camera.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvmm_contentpipe.so:system/lib/libnvmm_contentpipe.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvmm_image.so:system/lib/libnvmm_image.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvmm_manager.so:system/lib/libnvmm_manager.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvmm_misc.so:system/lib/libnvmm_misc.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvmm_parser.so:system/lib/libnvmm_parser.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvmm_service.so:system/lib/libnvmm_service.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvmm_utils.so:system/lib/libnvmm_utils.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvmm_video.so:system/lib/libnvmm_video.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvmm_writer.so:system/lib/libnvmm_writer.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvmmlite.so:system/lib/libnvmmlite.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvmmlite_audio.so:system/lib/libnvmmlite_audio.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvmmlite_image.so:system/lib/libnvmmlite_image.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvmmlite_utils.so:system/lib/libnvmmlite_utils.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvmmlite_video.so:system/lib/libnvmmlite_video.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvodm_dtvtuner.so:system/lib/libnvodm_dtvtuner.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvodm_hdmi.so:system/lib/libnvodm_hdmi.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvodm_imager.so:system/lib/libnvodm_imager.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvodm_misc.so:system/lib/libnvodm_misc.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvodm_query.so:system/lib/libnvodm_query.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvomx.so:system/lib/libnvomx.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvomxilclient.so:system/lib/libnvomxilclient.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvos.so:system/lib/libnvos.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvparser.so:system/lib/libnvparser.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvrm.so:system/lib/libnvrm.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvsm.so:system/lib/libnvsm.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvtvmr.so:system/lib/libnvtvmr.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvwinsys.so:system/lib/libnvwinsys.so \
	$(VENDOR_FOLDER)/proprietary/lib/libnvwsi.so:system/lib/libnvwsi.so \
	$(VENDOR_FOLDER)/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
	$(VENDOR_FOLDER)/proprietary/lib/libtf_crypto_sst.so:system/lib/libtf_crypto_sst.so
